<a href="https://colab.research.google.com/github/ShynPham/pytorch_learning_journey/blob/main/00_pytorch_fundamentals_mynotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 .Pytorch Fundamentals

Resource NoteBook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Follow from video: Pytorch for deep learning & machine learning on youtube https://www.youtube.com/watch?v=V_xro1bcAuA


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

## Creating Tensors

In [ ]:
## Introduction to Tensors

## Creating Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 11])
vector

tensor([ 7, 11])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [ ]:
#TENSOR practice
TENSOR1 = torch.tensor([[[[1, 3, 2, 5],
                           [2, 4, 5, 3],
                           [3, 3, 2, 2],
                           [5, 3, 2, 3]]]])
TENSOR1

tensor([[[[1, 3, 2, 5],
          [2, 4, 5, 3],
          [3, 3, 2, 2],
          [5, 3, 2, 3]]]])

In [ ]:
TENSOR1.ndim

4

In [ ]:
TENSOR1[0]

tensor([[[1, 3, 2, 5],
         [2, 4, 5, 3],
         [3, 3, 2, 2],
         [5, 3, 2, 3]]])

In [ ]:
TENSOR1.shape

torch.Size([1, 1, 4, 4])

###Naming:

scalar and vector use lowercase letter


vector and tensor use uppercase letter

### Random Tensor

**Why random tensors?**

Random tensor are important because the way many nerual networks learn is that they start with tensors full of random number and then adjust those random numbers to better reprsent the data

`Start with random number -> look at the data -> update random number -> look at the data -> update random number`

In [ ]:
#Create a random tensor of size (3, 4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1055, 0.2910, 0.2415, 0.3569],
        [0.3518, 0.7894, 0.1463, 0.6978],
        [0.4824, 0.7736, 0.2719, 0.6943]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224, 224, 3)) #height, width, colour(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.2719, 0.1161, 0.2116, 0.8452],
         [0.4566, 0.7259, 0.5873, 0.4903],
         [0.3375, 0.4482, 0.0130, 0.3315]],

        [[0.7955, 0.9426, 0.8217, 0.8558],
         [0.1718, 0.4409, 0.6447, 0.9289],
         [0.1035, 0.7054, 0.4837, 0.8119]]])

###Zero and ones

In [ ]:
#create a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

#Creating a range of tensors and tensors-like

In [ ]:
# Usr torch.range()

one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# creating tensor like
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

**Note:** Tensor dataypes is one of the 3 big errors you'll encounter during pythorch and deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:

# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor (e.g float32 or float16 can google for what kind of data type are there)
                               device=None, # What devices is your tensor on
                               requires_grad=False) # Whether or not to track gradients with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
# FLoat 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Gettinng information with tensor (tensor attribute)


1. Tensor not right datatype  - to do get datatype from a tensor, can use `tensor.type`
2. Tensor not right shape - to get shape from a tensor, an use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2453, 0.2625, 0.1529, 0.9482],
        [0.6517, 0.0532, 0.3376, 0.6014],
        [0.0034, 0.8412, 0.3780, 0.7413]])

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Data of tensor: {some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device of tensor:{some_tensor.device}")

tensor([[0.2453, 0.2625, 0.1529, 0.9482],
        [0.6517, 0.0532, 0.3376, 0.6014],
        [0.0034, 0.8412, 0.3780, 0.7413]])
Data of tensor: torch.float32
Shape of tensor:torch.Size([3, 4])
Device of tensor:cpu


In [ ]:
#Code for myself
tensor_testing = torch.rand([3,3],
                            dtype=torch.float32,
                            device="cpu")
tensor_testing

tensor([[0.3874, 0.9836, 0.2632],
        [0.7629, 0.7092, 0.5169],
        [0.4541, 0.6404, 0.6753]])

In [ ]:
print(tensor_testing)
print(f"Data of tensor:{tensor_testing.dtype}")
print(f"Shape of tensor:{tensor_testing.shape}")
print(f"Device of tensor:{tensor_testing.device}")

tensor([[0.3874, 0.9836, 0.2632],
        [0.7629, 0.7092, 0.5169],
        [0.4541, 0.6404, 0.6753]])
Data of tensor:torch.float32
Shape of tensor:torch.Size([3, 3])
Device of tensor:cpu


### Manipulating Tensor( tensor operations )

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication;

In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Divide 10
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor,10) # multiplication

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication

Two main ways of perofrming multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication ( dot product )

More information on multiplying matrix: https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix multplication needs to satisfy:

1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` wont work  (@ basically mean matmul)
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. THe resulting matrix has the shape of the **outer dimensons**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3)).shape

torch.Size([3, 3])

In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplicaiton by hand

1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
#using for loop (slower)
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.65 ms, sys: 0 ns, total: 1.65 ms
Wall time: 1.77 ms


tensor(14)

In [ ]:
# using pytorch implementation (faster)
%%time
torch.matmul(tensor, tensor)

CPU times: user 77 µs, sys: 0 ns, total: 77 µs
Wall time: 80.8 µs


tensor(14)

### One of the most common errors in deep learning: Shape Error

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor(([1, 2],
                         [3, 4],
                         [5, 6],))
tensor_B = torch.tensor(([7, 10],
                         [8, 11],
                         [9, 12]))

##torch.mm(tensor_A, tensor_B) ##torch.mm is the same as torch.matmul

##torch.matmul(tensor_A, tensor_B)


NameError: name 'torch' is not defined

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using transpose

A **Transpose** switches the axes or dimesnsion of a given tensor.

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# The matrix operation work because of the tensor_b is tranposed
print(f"Original shape: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shape: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimmension must match")
print("Output: \n")
output = torch.mm (tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shape: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shape: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimmension must match
Output: 

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


In [ ]:
#Learning myself

tensor_a = torch.tensor(([1, 2],
                         [4, 5],
                         [7, 8]))
tensor_b = torch.tensor(([1, 2, 3],
                         [3, 4, 5]))
tensor_b.T
print(f"Original shape of tensor_b = {tensor_b.shape}")
print(f"New shape of tensor_b = {tensor_b.T.shape}")
torch.mm (tensor_a, tensor_b)

Original shape of tensor_b = torch.Size([2, 3])
New shape of tensor_b = torch.Size([3, 2])


tensor([[ 7, 10, 13],
        [19, 28, 37],
        [31, 46, 61]])

## Finding the min, max, mrean, sum, etc ( tensor aggregation)


In [ ]:
# Create a tensor
x= torch.arange(1, 100, 10)  #torch.range will be remove, use torch.arange in the future instead (03/12/2025)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#FInd the mean  - note: the torch.mean() function requires a tensor of float 32 datatype to work
torch.mean(x.type(torch.float32))

tensor(46.)

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the postion of tensor that has the minimum value with argmin() -> return inde position of target tensor where the minimum value target occure
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has maximum value with argmax()
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing

* Reshaping - reshape an input tensor to a defined shaped
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - Combind multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way



In [ ]:
#Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x ( because a view of a tensor share the same meory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1
)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch,squeeze() - remove all single dimension from a target tensor
print(f"Pervious tensor {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")

Pervious tensor tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

New shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specfic dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueeze = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueeze}")
print(f"\nNew shape: {x_unsqueeze.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearrange the dimension of a target tensor in a specific order
x_original = torch.rand(size=(224, 224, 3)) #[height, width, color_channels]

#Permute the original tensor to rearrange the axis(or dim) order

x_premuted = x_original.permute(2, 0, 1) # shift axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_premuted.shape}") # [colours_chanels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0]
x_original

tensor([[[0.2998, 0.1279, 0.2191],
         [0.7182, 0.8203, 0.5017],
         [0.0632, 0.4044, 0.6637],
         ...,
         [0.2775, 0.1005, 0.7228],
         [0.6912, 0.4044, 0.8610],
         [0.8554, 0.0570, 0.9655]],

        [[0.6084, 0.1258, 0.1101],
         [0.4368, 0.1954, 0.7157],
         [0.7250, 0.4227, 0.4431],
         ...,
         [0.5633, 0.8987, 0.7799],
         [0.6994, 0.8203, 0.2221],
         [0.6296, 0.8221, 0.5986]],

        [[0.3471, 0.8233, 0.8864],
         [0.1443, 0.3304, 0.6195],
         [0.1968, 0.7123, 0.9335],
         ...,
         [0.2105, 0.6327, 0.0182],
         [0.2395, 0.7291, 0.3126],
         [0.0272, 0.7256, 0.8781]],

        ...,

        [[0.6344, 0.7808, 0.5428],
         [0.1014, 0.7556, 0.6874],
         [0.2815, 0.5291, 0.7219],
         ...,
         [0.4594, 0.3046, 0.5162],
         [0.5688, 0.5752, 0.6491],
         [0.2160, 0.5963, 0.0325]],

        [[0.5183, 0.9559, 0.0838],
         [0.4926, 0.4351, 0.8421],
         [0.

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

### Indexing (selecting data from tensor)
Indexing with PyTorch is similar to indexing with Numpy


In [ ]:
#Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let put index on our new tensnor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle brracket (dim=1)
x[0][[0]]

tensor([[1, 2, 3]])

In [ ]:
x[0][0][0]
x[0][2][2]

tensor(9)

In [ ]:
# YOu can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all value of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [ ]:
#Index on x to reutn 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

# PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor =  torch.from_numpy(array) # warning: when oconverting from numpy -> pytorch, pytorch reflects numpy's deffault datatype off float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Change the value  of arrray, what will this do to `tensor`?

array = array + 1

array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, what happend to `numpy_tensor`??
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility ( trying to take random out of random)

In short how a nerual network learns:

`start with random number -> tensor operation -> update random numbers to try tnad make them better representation of the data -> agian -> agian -> etc...`

TO reduce the randomness in enural networks and Pytorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness


In [ ]:
import torch

# Create two random tensor

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.7396, 0.7252, 0.8345, 0.4356],
        [0.8397, 0.9974, 0.0601, 0.3776],
        [0.0821, 0.0496, 0.5220, 0.3143]])
tensor([[0.4071, 0.6998, 0.7020, 0.7352],
        [0.5412, 0.3707, 0.6167, 0.0749],
        [0.6755, 0.9072, 0.6092, 0.6735]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensor
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility and random seed:
* https://pytorch.org/docs/stable/notes/randomness.html


## Runnning tensors and PyTorch objects on the GPUs ( and making faster computation)

GPUs = faster computation on numbers, CUDA + Nvidia hardware + Pytorch working behind the scence.

### 1. Getting a GPU

* 1: Use google collab pro - Easist
* 2: Buy your own GPU
* 3: Use cloud computing

### 2. Check for GPU access with Pytorch

In [ ]:
# Check for GPU access with pytorch
import torch
torch.cuda.is_available()

True

For Pytorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic on pytorhc webiste.

E.G run on GPU if avalabile, else on CPU.

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU
The reason why we want our tensors/models to run on GPU is to get result in faster computation

In [ ]:
# Create a tensor ( default on the CPU)
tensor = torch.tensor([1, 2, 3])

#Tensor not on GPu
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
### 4. Moving tensors back to the CPU
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# TO fix the GPU tensor with numpy issue, we can first set it to the CPU
tensor_back_to_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_to_cpu

array([1, 2, 3])

## Excercises and Extra-curriculum